### ISSUE TITLE
An option to disable trim

### ISSUE THREAD

**Issue by HardeepAsrani** [IndigoUnited/js-deep-compact#16]
I was using this in a React project and while updating the state, it won't work properly as it will remove whitespaces, so if the text area is empty and I want to "I'm here," then it will just remove the space after "I'm" and won't let me put spaces, so that sucks.

**Comment by satazor** [comment]
Can you make a PR adding an option to disable trim?

**Comment by HardeepAsrani** [comment]
@satazor

Sure, can you just explain what this line does?

```value = subject[prop] = value.trim();```

Never seen a syntax with two assign operators, so I'm little confused about it.

Also, I'd convert the entire script to ES6 syntax, if that's fine by you?

**Comment by HardeepAsrani** [comment]
FYI, here's the current code I'm using on my project, in case you notice some issues:

```
// A fork of deep-compact package as it had some issues.
const notEmpty = ( value, prop, subject ) => {
    let key;

    if ( Array.isArray( value ) ) {
        return value.length > 0;
    }

    if ( isPlainObject( value ) ) {
        for ( key in value ) {
            return true;
        }

        return false;
    }

    if ( typeof value === 'string' ) {
        value = subject[prop] = value;

        return value.length > 0;
    }

    return value != null;
}

export const compact = value => deepFilter( value, notEmpty );
```
